using InnerNetClient_GameState__Enum = DBDDAJAICFN_DKEKFCCGGEO__Enum;
using PlayerControl = APNNOJFGDGP;
using Player_Die_Reason__Enum = LKBAAGPFMCB__Enum;
using MeetingHud = APFHIONIINA;
using InnerNetClient = DBDDAJAICFN;
using InnerNet_DisconnectReasons__Enum = OBELNHOKKLD__Enum;
using HqHudOverrideTask = OFCAMODPCOA;
using HudOverrideTask = MHKPCHGHHOK;
using ChatController = LOGKEMANPPL;
using AmongUsClient = HJNEPPHDLBA;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Joined = DBDDAJAICFN_DKEKFCCGGEO__Enum_Joined;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Ended = DBDDAJAICFN_DKEKFCCGGEO__Enum_Ended;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Started = DBDDAJAICFN_DKEKFCCGGEO__Enum_Started;
#define PlayerControl_FixedUpdate_Trampoline APNNOJFGDGP_FixedUpdate
#define PlayerControl_GetTruePosition_Trampoline APNNOJFGDGP_GetTruePosition
#define PlayerControl_Die_Trampoline APNNOJFGDGP_Die
#define MeetingHud_Close_Trampoline APFHIONIINA_Close
#define MeetingHud_Start_Trampoline APFHIONIINA_Start
#define InnerNetClient_FixedUpdate_Trampoline DBDDAJAICFN_FixedUpdate
#define InnerNetClient_Disconnect_Trampoline DBDDAJAICFN_LJKOGKNHGGA
#define HqHudOverrideTask_Initialize_Trampoline OFCAMODPCOA_Initialize
#define HqHudOverrideTask_Complete_Trampoline OFCAMODPCOA_Complete
#define HudOverrideTask_Initialize_Trampoline MHKPCHGHHOK_Initialize
#define HudOverrideTask_Complete_Trampoline MHKPCHGHHOK_Complete
#define ChatController_AddChat_Trampoline LOGKEMANPPL_AddChat
#define InnerNetClient_StartRpc_Trampoline DBDDAJAICFN_StartRpc
#define MessageWriter_Write_String_Trampoline MessageWriter_Write_6
#define AmongUsClient_OnPlayerJoined_Trampoline HJNEPPHDLBA_LKMONKFOADB