using Player_Die_Reason__Enum = DBLJKMDLJIF__Enum;
using PlayerControl = FFGALNAPKCD;
using InnerNetClient = KHNHJFFECBP;
using InnerNetClient_GameState__Enum = KHNHJFFECBP_KGEKNMMAKKN__Enum;
using InnerNet_DisconnectReasons__Enum = GHMBCKNECJF__Enum;
using MeetingHud = OOCJALPKPEP;
using HqHudOverrideTask = NIAFLKKACLE;
using HudOverrideTask = LFOILEODBMA;
using ChatController = GEHKHGLKFHE;
using AmongUsClient = FMLLKEACGIO;
using PlayerData = EGLJNOMOGNP_DCJMABDDJCF;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Joined = KHNHJFFECBP_KGEKNMMAKKN__Enum_Joined;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Started = KHNHJFFECBP_KGEKNMMAKKN__Enum_Started;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Ended = KHNHJFFECBP_KGEKNMMAKKN__Enum_Ended;
#define PlayerControl_GetTruePosition_Trampoline FFGALNAPKCD_GetTruePosition
#define PlayerControl_Die_Trampoline FFGALNAPKCD_Die
#define PlayerControl_FixedUpdate_Trampoline FFGALNAPKCD_FixedUpdate
#define InnerNetClient_FixedUpdate_Trampoline KHNHJFFECBP_FixedUpdate
#define InnerNetClient_Disconnect_Trampoline KHNHJFFECBP_AMKMODDAFOO
#define InnerNetClient_HandleGameDataInner_Trampoline KHNHJFFECBP_LMFMFBMONOO
#define InnerNetClient_StartRpc_Trampoline KHNHJFFECBP_StartRpc
#define MeetingHud_Close_Trampoline OOCJALPKPEP_Close
#define MeetingHud_Start_Trampoline OOCJALPKPEP_Start
#define HqHudOverrideTask_Initialize_Trampoline NIAFLKKACLE_Initialize
#define HqHudOverrideTask_Complete_Trampoline NIAFLKKACLE_Complete
#define HudOverrideTask_Initialize_Trampoline LFOILEODBMA_Initialize
#define HudOverrideTask_Complete_Trampoline LFOILEODBMA_Complete
#define ChatController_AddChat_Trampoline GEHKHGLKFHE_AddChat
#define MessageWriter_Write_Byte_Trampoline MessageWriter_Write_1
#define AmongUsClient_OnPlayerJoined_Trampoline FMLLKEACGIO_BIEPKGFMACN
#define PlayerControl_RPC_SetInfected FFGALNAPKCD_RpcSetInfected
#define PlayerControl_RemoveInfected FFGALNAPKCD_RemoveInfected
#define PlayerControl_GetData FFGALNAPKCD_get_Data
#define PlayerControl_TypeInfo FFGALNAPKCD__TypeInfo
#define IsImposter DAPKNDBLKIA