using InnerNetClient_GameState__Enum = InnerNetClient_IFLBIJFJPMK__Enum;
using Player_Die_Reason__Enum = NPLMBOLMMLB__Enum;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Joined = InnerNetClient_IFLBIJFJPMK__Enum_Joined;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Ended = InnerNetClient_IFLBIJFJPMK__Enum_Ended;
#define PlayerControl_FixedUpdate_Trampoline PlayerControl_FixedUpdate
#define PlayerControl_GetTruePosition_Trampoline PlayerControl_GetTruePosition
#define PlayerControl_Die_Trampoline PlayerControl_Die
#define MeetingHud_Close_Trampoline MeetingHud_Close
#define MeetingHud_Start_Trampoline MeetingHud_Start
#define InnerNetClient_FixedUpdate_Trampoline InnerNetClient_FixedUpdate