using Player_Die_Reason__Enum = NGMJAFCBKGP__Enum;
using PlayerControl = BHHCHKFKPOE;
using InnerNetClient = KIFAJMBCIGE;
using InnerNetClient_GameState__Enum = KIFAJMBCIGE_HBGBMLJMJJN__Enum;
using InnerNet_DisconnectReasons__Enum = IKBPJNLHAMP__Enum;
using MeetingHud = CHDFKFMCJFM;
using HqHudOverrideTask = PODCFBLFNLO;
using HudOverrideTask = OOCOMHBLGPD;
using ChatController = BNGAGGNFPLK;
using AmongUsClient = OIMFAEOPLBD;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Joined = KIFAJMBCIGE_HBGBMLJMJJN__Enum_Joined;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Started = KIFAJMBCIGE_HBGBMLJMJJN__Enum_Started;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Ended = KIFAJMBCIGE_HBGBMLJMJJN__Enum_Ended;
#define PlayerControl_GetTruePosition_Trampoline BHHCHKFKPOE_GetTruePosition
#define PlayerControl_Die_Trampoline BHHCHKFKPOE_Die
#define PlayerControl_FixedUpdate_Trampoline BHHCHKFKPOE_FixedUpdate
#define InnerNetClient_FixedUpdate_Trampoline KIFAJMBCIGE_FixedUpdate
#define InnerNetClient_Disconnect_Trampoline KIFAJMBCIGE_FJANKNOCFEE
#define InnerNetClient_StartRpc_Trampoline KIFAJMBCIGE_StartRpc
#define MeetingHud_Close_Trampoline CHDFKFMCJFM_Close
#define MeetingHud_Start_Trampoline CHDFKFMCJFM_Start
#define HqHudOverrideTask_Initialize_Trampoline PODCFBLFNLO_Initialize
#define HqHudOverrideTask_Complete_Trampoline PODCFBLFNLO_Complete
#define HudOverrideTask_Initialize_Trampoline OOCOMHBLGPD_Initialize
#define HudOverrideTask_Complete_Trampoline OOCOMHBLGPD_Complete
#define AmongUsClient_OnPlayerJoined_Trampoline OIMFAEOPLBD_KKBDFAFCJIF
#define MessageWriter_Write_Byte_Trampoline MessageWriter_Write_1
#define InnerNetClient_HandleGameDataInner_Trampoline KIFAJMBCIGE_KGBAIJNMIKO
