using Player_Die_Reason__Enum = EGEEFBOLHLP__Enum;
using PlayerControl = PPHGCHMFMLI;
using InnerNetClient = FIMOOCIGOAO;
using InnerNetClient_GameState__Enum = FIMOOCIGOAO_KBCHFKCGJKG__Enum;
using InnerNet_DisconnectReasons__Enum = GIDBHAMOKEA__Enum;
using MeetingHud = ILMBELNBDMA;
using HqHudOverrideTask = NPILPHBNAIC;
using HudOverrideTask = OGOEIBLEPKK;
using ChatController = KLDOCKJFNJL;
using AmongUsClient = NJGFKJNAEMN;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Joined = FIMOOCIGOAO_KBCHFKCGJKG__Enum_Joined;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Started = FIMOOCIGOAO_KBCHFKCGJKG__Enum_Started;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Ended = FIMOOCIGOAO_KBCHFKCGJKG__Enum_Ended;
#define PlayerControl_GetTruePosition_Trampoline PPHGCHMFMLI_GetTruePosition
#define PlayerControl_Die_Trampoline PPHGCHMFMLI_Die
#define PlayerControl_FixedUpdate_Trampoline PPHGCHMFMLI_FixedUpdate
#define InnerNetClient_FixedUpdate_Trampoline FIMOOCIGOAO_FixedUpdate
#define InnerNetClient_Disconnect_Trampoline FIMOOCIGOAO_OEIIMGAFPOO
#define InnerNetClient_StartRpc_Trampoline FIMOOCIGOAO_StartRpc
#define MeetingHud_Close_Trampoline ILMBELNBDMA_Close
#define MeetingHud_Start_Trampoline ILMBELNBDMA_Start
#define HqHudOverrideTask_Initialize_Trampoline NPILPHBNAIC_Initialize
#define HqHudOverrideTask_Complete_Trampoline NPILPHBNAIC_Complete
#define HudOverrideTask_Initialize_Trampoline OGOEIBLEPKK_Initialize
#define HudOverrideTask_Complete_Trampoline OGOEIBLEPKK_Complete
#define ChatController_AddChat_Trampoline KLDOCKJFNJL_AddChat
#define AmongUsClient_OnPlayerJoined_Trampoline NJGFKJNAEMN_LOFILOLGOGD
#define MessageWriter_Write_String_Trampoline MessageWriter_Write_6