using Player_Die_Reason__Enum = BMOPDKNGEHP__Enum;
using PlayerControl = LBADNGJPJGH;
using InnerNetClient = IFEMMDOEKDL;
using InnerNetClient_GameState__Enum = IFEMMDOEKDL_MDKCICGKNBA__Enum;
using InnerNet_DisconnectReasons__Enum = JPONPMHDFBL__Enum;
using MeetingHud = LMJOGIIMCMB;
using HqHudOverrideTask = KEKFAIIFGLL;
using HudOverrideTask = JGMIPAPJPGD;
using ChatController = FLICDOHEDCM;
using AmongUsClient = KNKBHCOHCOM;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Joined = IFEMMDOEKDL_MDKCICGKNBA__Enum_Joined;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Started = IFEMMDOEKDL_MDKCICGKNBA__Enum_Started;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Ended = IFEMMDOEKDL_MDKCICGKNBA__Enum_Ended;
#define PlayerControl_GetTruePosition_Trampoline LBADNGJPJGH_GetTruePosition
#define PlayerControl_Die_Trampoline LBADNGJPJGH_Die
#define PlayerControl_FixedUpdate_Trampoline LBADNGJPJGH_FixedUpdate
#define InnerNetClient_FixedUpdate_Trampoline IFEMMDOEKDL_FixedUpdate
#define InnerNetClient_Disconnect_Trampoline IFEMMDOEKDL_HFDOHDBDGGL
#define InnerNetClient_StartRpc_Trampoline IFEMMDOEKDL_StartRpc
#define MeetingHud_Close_Trampoline LMJOGIIMCMB_Close
#define MeetingHud_Start_Trampoline LMJOGIIMCMB_Start
#define HqHudOverrideTask_Initialize_Trampoline KEKFAIIFGLL_Initialize
#define HqHudOverrideTask_Complete_Trampoline KEKFAIIFGLL_Complete
#define HudOverrideTask_Initialize_Trampoline JGMIPAPJPGD_Initialize
#define HudOverrideTask_Complete_Trampoline JGMIPAPJPGD_Complete
#define AmongUsClient_OnPlayerJoined_Trampoline KNKBHCOHCOM_DMGHDNOADBO
#define MessageWriter_Write_Byte_Trampoline MessageWriter_Write_1
#define InnerNetClient_HandleGameDataInner_Trampoline IFEMMDOEKDL_BCNEDMEDMKH