using Player_Die_Reason__Enum = OOBDLHLDDAF__Enum;
using PlayerControl = JENJGDMOEOC;
using InnerNetClient = FMJPJKCNIKM;
using InnerNetClient_GameState__Enum = FMJPJKCNIKM_ONHEJJJIKDI__Enum;
using InnerNet_DisconnectReasons__Enum = CLFGKJHHBOK__Enum;
using MeetingHud = NEOCOBOAGFJ;
using HqHudOverrideTask = AFFPOFMFHEF;
using HudOverrideTask = KALDPINPHCD;
using ChatController = BPPJFAOEOMH;
using AmongUsClient = MMMGPAPEEBJ;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Joined = FMJPJKCNIKM_ONHEJJJIKDI__Enum_Joined;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Started = FMJPJKCNIKM_ONHEJJJIKDI__Enum_Started;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Ended = FMJPJKCNIKM_ONHEJJJIKDI__Enum_Ended;
#define PlayerControl_GetTruePosition_Trampoline JENJGDMOEOC_GetTruePosition
#define PlayerControl_Die_Trampoline JENJGDMOEOC_Die
#define PlayerControl_FixedUpdate_Trampoline JENJGDMOEOC_FixedUpdate
#define InnerNetClient_FixedUpdate_Trampoline FMJPJKCNIKM_FixedUpdate
#define InnerNetClient_Disconnect_Trampoline FMJPJKCNIKM_AAKFLNMJNBJ
#define InnerNetClient_StartRpc_Trampoline FMJPJKCNIKM_StartRpc
#define MeetingHud_Close_Trampoline NEOCOBOAGFJ_Close
#define MeetingHud_Start_Trampoline NEOCOBOAGFJ_Start
#define HqHudOverrideTask_Initialize_Trampoline AFFPOFMFHEF_Initialize
#define HqHudOverrideTask_Complete_Trampoline AFFPOFMFHEF_Complete
#define HudOverrideTask_Initialize_Trampoline KALDPINPHCD_Initialize
#define HudOverrideTask_Complete_Trampoline KALDPINPHCD_Complete
#define AmongUsClient_OnPlayerJoined_Trampoline MMMGPAPEEBJ_NDONNDIFBON
#define MessageWriter_Write_Byte_Trampoline MessageWriter_Write_1
#define InnerNetClient_HandleGameDataInner_Trampoline FMJPJKCNIKM_AOAKDFPIOOA