using InnerNetClient_GameState__Enum = DNAFMCDBMCI_JPCEFDHGHAK__Enum;
using PlayerControl = GLHCHLEDNBA;
using Player_Die_Reason__Enum = CCCHKEBONBN__Enum;
using MeetingHud = GPOHFPAIEMA;
using InnerNetClient = DNAFMCDBMCI;
using InnerNet_DisconnectReasons__Enum = NCBONGGBCNE__Enum;
using HqHudOverrideTask = MMPIJGKLMDC;
using HudOverrideTask = GFBKIHICFNI;
using ChatController = MLINJDBIIEC;
using AmongUsClient = JNFEHNLGIFF;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Joined = DNAFMCDBMCI_JPCEFDHGHAK__Enum_Joined;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Ended = DNAFMCDBMCI_JPCEFDHGHAK__Enum_Ended;
InnerNetClient_GameState__Enum InnerNetClient_GameState__Enum_Started = DNAFMCDBMCI_JPCEFDHGHAK__Enum_Started;
#define PlayerControl_FixedUpdate_Trampoline GLHCHLEDNBA_FixedUpdate
#define PlayerControl_GetTruePosition_Trampoline GLHCHLEDNBA_GetTruePosition
#define PlayerControl_Die_Trampoline GLHCHLEDNBA_Die
#define MeetingHud_Close_Trampoline GPOHFPAIEMA_Close
#define MeetingHud_Start_Trampoline GPOHFPAIEMA_Start
#define InnerNetClient_FixedUpdate_Trampoline DNAFMCDBMCI_FixedUpdate
#define InnerNetClient_Disconnect_Trampoline DNAFMCDBMCI_GPKBCOKMFHK
#define HqHudOverrideTask_Initialize_Trampoline MMPIJGKLMDC_Initialize
#define HqHudOverrideTask_Complete_Trampoline MMPIJGKLMDC_Complete
#define HudOverrideTask_Initialize_Trampoline GFBKIHICFNI_Initialize
#define HudOverrideTask_Complete_Trampoline GFBKIHICFNI_Complete
#define ChatController_AddChat_Trampoline MLINJDBIIEC_AddChat
#define InnerNetClient_StartRpc_Trampoline DNAFMCDBMCI_StartRpc
#define MessageWriter_Write_String_Trampoline MessageWriter_Write_6
#define AmongUsClient_OnPlayerJoined_Trampoline JNFEHNLGIFF_IKDNNJNBKBO